# Generated by Django 3.0.3 on 2020-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=30),
        ),
    ]
